server:
  # 服务端口号
  port: 18080

spring:
  application:
    name: tanhua-app-server
  # redis 配置
  redis:
    host: 192.168.80.129
    port: 6379
    password: 806823
  cloud:
    # nacos 配置
    nacos:
      discovery:
        server-addr: 192.168.80.129:8848
      config:
        server-addr: 192.168.80.129:8848

# dubbo 配置
dubbo:
  registry:
    address: spring-cloud://localhost
    check: false
  consumer:
    check: false # 关闭自动检查
    timeout: 3000
    retries: 0

tanhua:
  # sms 短信
  sms:
    signName: 黑马旅游网
    templateCode: SMS_205877727
    accessKey: LTAI4GAX9FhwjEhVjxJb9ugL
    secret: dgpqJiegJgcZyZuQ5ul7tIoweFFY8B
  # oss 存储
  oss:
    accessKey: LTAI5tLusUCwhsSwSueRXnCu
    secret: iiyT1Xh9yfBJ9yixvg6MGqnZLpmAkX
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucketName: tanhua0823
    url: https://tanhua0823.oss-cn-shanghai.aliyuncs.com/
  # 百度人脸识别配置
  aip:
    appId: 30865459
    apiKey: 0nnsoeDWvymtVg7GsXvZjc57
    secretKey: OgkjDo4BQtf5zaMwx1Wtpzg1dNEzok83
  # 环信IM配置
  huanxin:
    appkey: 1111230304175061#tanhua
    clientId: YXA6APsROq6LTimLTOLi_f4I1Q
    clientSecret: YXA6eTjZW2Ku7VBfF4xt2RATJqWNzq0
  # 默认推荐用户列表
  default:
    recommend:
      users: 2,3,8,10,18,20,24,29,27,32,36,37,56,64,75,88